# Generated by Django 4.2 on 2023-08-03 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colors',
        ),
    ]
