# Generated by Django 4.2 on 2023-08-07 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('transactions', '0003_delete_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='merchant_category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.merchant'),
        ),
    ]
