# Generated by Django 4.2 on 2023-11-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_mcc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mcc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
