# Generated by Django 4.2 on 2023-12-07 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_mcc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_credit',
        ),
    ]
