# Generated by Django 4.2 on 2023-08-07 00:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default='0000', max_length=5, unique=True)),
                ('description', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
